# Generated by Django 5.1.6 on 2025-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="pay_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
