# Generated by Django 5.1.6 on 2025-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orders_pay_link_orders_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="pay_link",
        ),
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="customer_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="total_cost",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
