# Generated by Django 5.1.6 on 2025-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_delete_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="pay_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
