# Generated by Django 5.1.6 on 2025-02-14 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_order_total_amount_order_pay_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pay_link",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
