# Generated by Django 5.1.6 on 2025-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_order_pay_link_remove_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.JSONField(default=list),
        ),
    ]
