# Generated by Django 5.1.6 on 2025-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="chat_id",
            field=models.PositiveBigIntegerField(default="2083239343"),
        ),
    ]
