# Generated by Django 5.1.6 on 2025-03-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_lang_code",
            field=models.CharField(default="uz", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("click", "Click"), ("payme", "Payme")],
                max_length=20,
                null=True,
                verbose_name="payment method",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="amount"
            ),
        ),
    ]
