# Generated by Django 5.1.6 on 2025-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bot_order_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="bot_order_id"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="chat_id",
            field=models.BigIntegerField(blank=True, default="2083239343", null=True),
        ),
    ]
